# Use the official Node.js 16 image as a parent image
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your Vue.js frontend source code
COPY . .

# Build the app for production
RUN npm run build

# Install a simple HTTP server to serve static content
RUN npm install -g http-server

# Expose the port the app runs on
EXPOSE 8080

# Serve the app using http-server
CMD ["http-server", "dist"]
